---
# Joins CentOS 7 machine(s) to AD domain

- name: Modify /etc/resolv.conf to point to DC
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: Join CentOS 7 machine(s) to AD domain
  expect:
    command: realm join -U "{{ domain_admin }}"@"{{ domain }}" "{{ domain }}" 
    responses:
      (.*)@(.*): "{{ domain_admin_pw }}"
